/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BCHAN_H_RPCGEN
#define _BCHAN_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct bchan_msg {
	u_int seqnum;
	char *msg1;
	char *msg2;
};
typedef struct bchan_msg bchan_msg;

struct bchan_res {
	u_int result;
	char *msg1;
};
typedef struct bchan_res bchan_res;

#define BCHAN_PROG 0x20005002
#define BCHANV 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALLBACK1 1
extern  enum clnt_stat callback1_1(bchan_msg *, bchan_res *, CLIENT *);
extern  bool_t callback1_1_svc(bchan_msg *, bchan_res *, struct svc_req *);
extern int bchan_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALLBACK1 1
extern  enum clnt_stat callback1_1();
extern  bool_t callback1_1_svc();
extern int bchan_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bchan_msg (XDR *, bchan_msg*);
extern  bool_t xdr_bchan_res (XDR *, bchan_res*);

#else /* K&R C */
extern bool_t xdr_bchan_msg ();
extern bool_t xdr_bchan_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BCHAN_H_RPCGEN */
