/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FCHAN_H_RPCGEN
#define _FCHAN_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct fchan_msg {
	u_int seqnum;
	char *msg1;
	char *msg2;
};
typedef struct fchan_msg fchan_msg;

struct fchan_res {
	u_int result;
	char *msg1;
};
typedef struct fchan_res fchan_res;

struct read_args {
	u_int seqnum;
	u_int fileno;
	u_int off;
	u_int len;
	u_int flags;
};
typedef struct read_args read_args;

struct read_res {
	u_int eof;
	u_int flags;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct read_res read_res;

struct write_args {
	u_int seqnum;
	u_int fileno;
	u_int off;
	u_int len;
	u_int flags;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct write_args write_args;

#define FCHAN_PROG 0x20005001
#define FCHANV 1

#if defined(__STDC__) || defined(__cplusplus)
#define SENDMSG1 1
extern  enum clnt_stat sendmsg1_1(fchan_msg *, fchan_res *, CLIENT *);
extern  bool_t sendmsg1_1_svc(fchan_msg *, fchan_res *, struct svc_req *);
#define BIND_CONN_TO_SESSION1 2
extern  enum clnt_stat bind_conn_to_session1_1(void *, int *, CLIENT *);
extern  bool_t bind_conn_to_session1_1_svc(void *, int *, struct svc_req *);
#define READ 3
extern  enum clnt_stat read_1(read_args *, read_res *, CLIENT *);
extern  bool_t read_1_svc(read_args *, read_res *, struct svc_req *);
#define WRITE 4
extern  enum clnt_stat write_1(write_args *, int *, CLIENT *);
extern  bool_t write_1_svc(write_args *, int *, struct svc_req *);
extern int fchan_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SENDMSG1 1
extern  enum clnt_stat sendmsg1_1();
extern  bool_t sendmsg1_1_svc();
#define BIND_CONN_TO_SESSION1 2
extern  enum clnt_stat bind_conn_to_session1_1();
extern  bool_t bind_conn_to_session1_1_svc();
#define READ 3
extern  enum clnt_stat read_1();
extern  bool_t read_1_svc();
#define WRITE 4
extern  enum clnt_stat write_1();
extern  bool_t write_1_svc();
extern int fchan_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_fchan_msg (XDR *, fchan_msg*);
extern  bool_t xdr_fchan_res (XDR *, fchan_res*);
extern  bool_t xdr_read_args (XDR *, read_args*);
extern  bool_t xdr_read_res (XDR *, read_res*);
extern  bool_t xdr_write_args (XDR *, write_args*);

#else /* K&R C */
extern bool_t xdr_fchan_msg ();
extern bool_t xdr_fchan_res ();
extern bool_t xdr_read_args ();
extern bool_t xdr_read_res ();
extern bool_t xdr_write_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FCHAN_H_RPCGEN */
