/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fchan.h"

bool_t
xdr_fchan_msg (XDR *xdrs, fchan_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->seqnum))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg1, 1024))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg2, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fchan_res (XDR *xdrs, fchan_res *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg1, 512))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_args (XDR *xdrs, read_args *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->seqnum))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->fileno))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->off))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->len))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->seqnum);
		IXDR_PUT_U_LONG(buf, objp->fileno);
		IXDR_PUT_U_LONG(buf, objp->off);
		IXDR_PUT_U_LONG(buf, objp->len);
		IXDR_PUT_U_LONG(buf, objp->flags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->seqnum))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->fileno))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->off))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->len))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;

		} else {
		objp->seqnum = IXDR_GET_U_LONG(buf);
		objp->fileno = IXDR_GET_U_LONG(buf);
		objp->off = IXDR_GET_U_LONG(buf);
		objp->len = IXDR_GET_U_LONG(buf);
		objp->flags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->seqnum))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->fileno))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->off))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_args (XDR *xdrs, write_args *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->seqnum))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->fileno))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->off))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->len))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->seqnum);
		IXDR_PUT_U_LONG(buf, objp->fileno);
		IXDR_PUT_U_LONG(buf, objp->off);
		IXDR_PUT_U_LONG(buf, objp->len);
		IXDR_PUT_U_LONG(buf, objp->flags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->seqnum))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->fileno))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->off))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->len))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;

		} else {
		objp->seqnum = IXDR_GET_U_LONG(buf);
		objp->fileno = IXDR_GET_U_LONG(buf);
		objp->off = IXDR_GET_U_LONG(buf);
		objp->len = IXDR_GET_U_LONG(buf);
		objp->flags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->seqnum))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->fileno))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->off))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}
